workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    environment:
      java: 17
    scripts:
      - name: Build Android Debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
